#! /usr/bin/python3
import sys,os,subprocess,json
required_dirs = {
    '.archive',
    '.store',
    'extras'
}
ignore_dirs = {
    os.path.basename(__file__),
    '.git',
    '.gitignore',
    '.clangd',
    'bits'
}
commands = {}
dash = '-'*16

def command(func):
    assert commands.get(func.__name__)==None
    commands[func.__name__] = func
    return func

def nl_input(*prompts):
    s = ''
    while s=='': s = input(*prompts).strip()
    return s

def get_or_input(*prompts):
    if len(fields):
        return fields.pop()
    return nl_input(*prompts)

def get_or_default(default):
    global fields
    if len(fields):
        return fields.pop()
    return default
    
def read_state():
    with open('.cfd','r') as f:
        return json.load(f)

def write_state(state):
    with open('.cfd','w') as f:
        json.dump(state,f,indent=2)

def get_lang(target):
    with open('extras/langs.json','r') as f:
        for lang in json.load(f):
            if lang['name']==target: return lang
    raise ValueError(f"Language '{target}' not found in extras/langs.json")

def clear_uc(state):
    dirs = [d for d in os.listdir('.') if d not in ignore_dirs]
    print('Deleting entries from task \''+state['name']+'\'')
    print(*dirs)
    if 'tests' in dirs : dirs.remove('tests')
    subprocess.run(['rm']+dirs)
    subprocess.run(['rm','-r','tests'] )
    return True

def store_uc(state):
    path = '.store/'+state['name']
    if os.path.exists(path):
        print('Entry with name \''+path+'\' already exists')
        return False
    else: 
        dirs = [d for d in os.listdir('.') if d not in ignore_dirs]
        subprocess.run(['mkdir',path])
        subprocess.run(['mv']+dirs+[path])
        return True
        
def check_active():
    if os.path.exists('.cfd'):
        return read_state()
    else:
        print('Currently not working on anything')
        return None
        
def try_make_inactive():
    if os.path.exists('.cfd'):
        state = read_state()
        print('Already working on \''+state['name']+'\'')
        r = nl_input('Clear[c] or Store[s] or Abort[_] : ')
        if r=='c':
            return clear_uc(state)
        elif r=='s':
            return store_uc(state)
        else : return False
    else : return True

@command
def new():
    if not try_make_inactive(): return
    state = {}
    state['name'] = get_or_input('Name of task : ')
    state['lang'] = get_or_input('Language [py|cpp|..] : ')
    state['ansfile'] = get_or_default('ans.'+state['lang'])
    write_state(state)
    subprocess.run(['mkdir','tests'])
    if (lang:=get_lang(state['lang']))!=None:
        subprocess.run(['cp',lang['template'],state['ansfile']])
    else:
        with open(state['ansfile'],'w') as _ : pass        
        
@command
def addtest():
    if (_:=check_active())==None : return
    n = len(os.listdir('tests'))
    test = sys.stdin.read()
    with open('tests/'+str(n+1)+'.txt','w') as f:
        f.write(test)
    
@command
def clear():
    if (state:=check_active())==None : return
    clear_uc(state)

@command
def set():
    if (state:=check_active())==None : return
    for field in fields:
        attr,val = field.split('=')
        if state.get(attr)!=None and val!='':
            print(attr,':',state[attr],'->',val)
            state[attr] = val
    write_state(state)
    
@command
def store():
    if (state:=check_active())==None : return
    store_uc(state)
    
@command
def run():
    if (state:=check_active())==None : return
    lang = get_lang(state['lang'])
    env = os.environ.copy()
    env['ARGS'] = get_or_default('')
    env['ANSFILE'] = state['ansfile']
    result = subprocess.run(lang['comp-cmd'],shell=True,env=env)
    if result.returncode!=0: return

    tests = os.listdir('tests')
    tests.sort()
    if len(tests)==0:
        subprocess.run(lang['run-cmd'],env=env,shell=True)
        subprocess.run(lang['clean-cmd'],env=env,shell=True)
        return 
    for test in tests:
        print(dash*2,test,dash*2)
        with open('tests/'+test,'r') as iff:
            result = subprocess.run(lang['run-cmd'],
                           stdout=subprocess.PIPE, stdin=iff,
                           env=env, shell=True)
            print(dash,'O',dash*2,'O',dash)
            print(result.stdout.decode('utf-8'),end='')
    subprocess.run(lang['clean-cmd'],env=env,shell=True)

@command
def archive():
    if (state:=check_active())==None : return
    entry = state['name']+'_'+state['ansfile']
    if os.path.exists('.archive/'+entry):
        print('Entry with name \''+entry+'\' already exists')
    else:
        subprocess.run(['mv',state['ansfile'],'.archive/'+entry])
        clear_uc(state)

@command
def extract():
    name = get_or_input('Name of entry to extract : ')
    path = '.store/'+name+'/'
    if os.path.exists(path):
        if not try_make_inactive(): return
        dirs = [path+dir for dir in os.listdir(path)]
        subprocess.run(['mv']+dirs+['./'])
        subprocess.run(['rmdir',path])
    else:
        print('No entry with name \''+name+'\' in store')
    
#---------------------------entry_point---------------------------#
for dir in required_dirs:
    assert os.path.exists(dir)
ignore_dirs.update(required_dirs)

if len(sys.argv)>=2 and sys.argv[1] in commands:
    fields = sys.argv[2:][::-1]
    commands[sys.argv[1]]()
else:
    print('wat?')
    # later
